controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_lucky:
    path: /{_locale}/lucky/number
    controller: App\Controller\LuckyController::number
    methods: GET|POST
    locale: en
    condition: "context.getMethod() in ['GET', 'HEAD', 'POST']"
    requirements:
        _locale: en|fr

app_lucky_show:
    path: /lucky/number/{id}
    controller: App\Controller\LuckyController::showNumber
    methods: GET
    condition: "params['id'] < 52 and service('route_checker').check(request)"
    requirements:
        id: '\d+'
    defaults:
        id: 1


doc_shortcut:
    path: /doc
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        route: 'app_document'
        page: 'index'
        version: 'current'
        keepQueryParams: true
        keepRequestMethod: true
        ignoreAttributes: true


legacy_shortcut:
    path: /legacy/doc
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        path: 'https://laravel.com'
        permanent: true


engine:
    path: /engine
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: 'engine/index.html.twig'
        statusCode: 200
        maxAge: 86400
        sharedAge: 86400
        private: true

        context:
            site_name: 'Template'
            theme: 'dark'